change isDevVersion() to a const to work around TypeScript error TS2367
this error was about comparison always being false because the type had no overlap